version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: themobileprof
      POSTGRES_USER: themobileprof
      POSTGRES_PASSWORD: themobileprof
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://themobileprof:themobileprof@db:5432/themobileprof
      JWT_SECRET: your-production-jwt-secret
      JWT_EXPIRES_IN: 24h
      BCRYPT_ROUNDS: 12
      EMAIL_SERVICE_API_KEY: dummy
      EMAIL_FROM_ADDRESS: noreply@themobileprof.com
      SPONSORSHIP_CODE_LENGTH: 10
      MAX_SPONSORSHIP_DURATION_MONTHS: 12
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      MAX_FILE_SIZE: 5242880
      UPLOAD_PATH: ./uploads
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: npm start

volumes:
  db_data: 